version: '2'
services:
  selenium_chrome:
    image: selenium/standalone-firefox:89.0-20210618
  tests:
    build: .
    depends_on:
      - "selenium_chrome"
    volumes:
      - ./reports:/test_code/reports
      - /dev/shm:/dev/shm
    shm_size: '1g'